/**changes */
public with sharing class AccountController {
    public AccountController() {

    }
    public integer sub(Integer a,Integer b){
        return a-b;
    }
    public integer sub(Integer a,Integer b){
        return a*b;
    }

    public static Integer add(Integer a,Integer b){
        return a+b;
    }
    public integer div(Integer a,Integer b){
        return a/b;
    }
    public integer display(Integer a,Integer b){
        return a/b;
    }

}
